# Generated by Django 5.2 on 2025-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_carrinho_usuario_alter_itemcarrinho_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
